server {
    listen 80;
    server_name localhost;

    # Cấu hình serve thư mục static của React
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy các request API đến Backend container
    location /api {
        proxy_pass http://backend:8080/api;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Proxy các file tĩnh (CV, Avatar, Logo, Cover) đến Backend container
    location /avatars {
        proxy_pass http://backend:8080/avatars;
    }
    location /resumes {
        proxy_pass http://backend:8080/resumes;
    }
    location /logos {
        proxy_pass http://backend:8080/logos;
    }
    location /covers {
        proxy_pass http://backend:8080/covers;
    }
}
